INSERT INTO subjects (name) VALUES ('Marketing asoslari');
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM subjects WHERE name='Marketing asoslari') THEN INSERT INTO subjects(name) VALUES('Marketing asoslari'); END IF; END $$;

INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Marketing atamasi fanga qachon kiritildi?', '1904', '1905', '1902', '1901', '1902', 1 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Marketing nima?', 'Bozorda maxsulotni sotishdir', 'Talabni kondirishga karatilgan faoliyatdir', 'Extiyojni xisobga olmagan xolda ishlab chiqarilgan maxsulotni sotish', 'Iste''molchiga nima kerak bulsa ushani ishlab chiqarash va sotish', 'Iste''molchiga nima kerak bulsa ushani ishlab chiqarash va sotish', 1 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Marketing qanday tizimni ifodalaydi?', 'Sotish', 'Ishlab chiqarish', 'Ayirboshlash', 'Ishlab chiqarish va sotish', 'Ishlab chiqarish va sotish', 1 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Iste''molchilar huquqi va manfaatlarini ximoya qilish bo''yicha tashkil qilingan harakat nima deyiladi?', 'Konsyumerizm', 'Diversivikatsiya', 'Bixeyvorizm', 'Materializm', 'Konsyumerizm', 1 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Nima bozorda turli xil tovarlar yordamida aks ettirilgan ehtiyojlar majmuasini aks ettiradi?', 'Talabdir', 'Takliflar', 'Reklamalar', 'Narxlar', 'Talabdir', 1 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Tadbirkorlik va marketing faoliyati oldida turgan vazifalarni bajarishda yordam beruvchi bilim va ma''lumotlar nima deyiladi?', 'Axborotdir', 'Shartnoma', 'Buyruq', 'Qaydnoma', 'Axborotdir', 2 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Tovar va xizmatlar bozorida iste''molchining manfaatlarini ximoya qilishga qaratilgan qoida va yo''riqnomalar majmui nima?', 'Iste''molchining mustaqilligi', 'Sotuvchining huquqi', 'Davlat buyurtmasi', 'Korxonaning nizomi', 'Iste''molchining mustaqilligi', 2 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Firma assortimentini hech qanday aloqasi bo''lmagan mahsulotlar bilan to''ldirish qanday ataladi?', 'Konglomerat diversifikatsiyadir', 'Bixeyvorizm', 'Konsyumerizm', 'Marketing miks', 'Konglomerat diversifikatsiyadir', 3 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'O''rganilayotgan obektning o''tmishdagi va hozirgi ma''lumotlarini tahlil qilishga asoslangan ilmiy oldindan ko''ra bilish nima?', 'Prognozlash (bashorat qilish)', 'Analiz', 'Deduksiya', 'Sintez', 'Prognozlash (bashorat qilish)', 1 FROM subjects WHERE name='Marketing asoslari';
INSERT INTO questions (subject_id, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty) SELECT id, 'Alohida shaxslar o''rtasida kattaroq foyda olish uchun kurash nima deyiladi?', 'Raqobatdir', 'Duopoliya', 'Oligopoliya', 'Monopolsoniya', 'Raqobatdir', 1 FROM subjects WHERE name='Marketing asoslari';

